source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'carrierwave'
gem 'carrierwave-validators', path: "../..", :require => 'carrierwave/validators'
group :development, :test do
  gem 'sqlite3', "~> 1.3.9"
  gem 'rspec-rails', '~> 2.14.2'
end
